# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TinyYOLO-CoreML' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextRecognizer
  pod 'GPUImage', :git => 'https://github.com/BradLarson/GPUImage.git'
  pod 'SwiftOCR', :git => 'https://github.com/garnele007/SwiftOCR.git'
end
